# 1. Build Stage
FROM node:lts AS builder
WORKDIR /app

# install deps
COPY package.json package-lock.json ./
RUN npm ci

# build the frontend
COPY . .
RUN npm run build

# 2. Run Stage (Nginx)
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/conf.d/
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
